import smtplib
from email.message import EmailMessage
from app.config import settings

from email.utils import formataddr

DISPLAY_NAME = "MedSense AI"
FROM_EMAIL = settings.SMTP_USER 

def send_otp_email(to_email: str, otp: str, patient_name: str = "Patient") -> bool:
    """Send OTP recovery email with HTML template."""
    smtp_server = settings.SMTP_SERVER
    smtp_port = settings.SMTP_PORT
    smtp_user = settings.SMTP_USER
    smtp_pass = settings.SMTP_PASS
    
    if not smtp_user or not smtp_pass:
        print(f"SMTP mock: OTP {otp} for {patient_name} to {to_email}")
        return True
        
    try:
        msg = EmailMessage()
        msg['Subject'] = 'Your MedSense Account Recovery OTP'
        msg['From'] = formataddr((DISPLAY_NAME, FROM_EMAIL))
        msg['To'] = to_email
        msg['X-Priority'] = '1 (Highest)'
        
        text_content = (
            f"Hi {patient_name},\n\n"
            f"Your recovery OTP is: {otp}\n\n"
            f"Valid for 5 minutes only. Never share this code.\n\n"
            f"Thank you,\nThe MedSense Team"
        )
        
        html_content = f"""
        <html>
        <body style="font-family: sans-serif; color: #333;">
            <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                <h2 style="color: #6366f1;">Account Recovery</h2>
                <p>Hi {patient_name},</p>
                <p>Your recovery OTP is:</p>
                <div style="background: #f4f4f5; padding: 15px; text-align: center; font-size: 24px; font-weight: bold; letter-spacing: 5px; border-radius: 5px;">
                    {otp}
                </div>
                <p style="font-size: 13px; color: #666;">Valid for 5 minutes only. If you didn't request this, please ignore this email.</p>
                <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
                <p style="font-size: 12px; color: #999;">MedSense AI Healthcare Assistant</p>
            </div>
        </body>
        </html>
        """
        
        msg.set_content(text_content)
        msg.add_alternative(html_content, subtype='html')
        
        print(f"Connecting to SMTP server {smtp_server}:{smtp_port} for OTP...")
        with smtplib.SMTP(smtp_server, smtp_port, timeout=20) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
        print(f"OTP sent successfully to {to_email}")
        return True
    except smtplib.SMTPException as smtp_err:
        print(f"OTP SMTP Protocol Error for {to_email}: {smtp_err}")
        return False
    except Exception as e:
        import traceback
        print(f"OTP email failed for {to_email} (Network/Server Error): {e}")
        # traceback.print_exc()
        return False

def send_report_email(to_email: str, pdf_bytes: bytes, patient_name: str="Patient") -> bool:
    """Send Medical Report with professional HTML template."""
    smtp_server = settings.SMTP_SERVER
    smtp_port = settings.SMTP_PORT
    smtp_user = settings.SMTP_USER
    smtp_pass = settings.SMTP_PASS

    if not smtp_user or not smtp_pass:
        print(f"SMTP Credentials not set. Simulated sending email to {to_email}")
        return True
        
    try:
        msg = EmailMessage()
        msg['Subject'] = f'Medical Consultation Report: {patient_name}'
        msg['From'] = formataddr((DISPLAY_NAME, FROM_EMAIL))
        msg['To'] = to_email
        
        text_content = (
            f"Hello {patient_name},\n\n"
            f"Please find attached your MedSense AI medical consultation report.\n\n"
            f"Note: This report is generated by AI for informational purposes only.\n\n"
            f"Best Regards,\nThe MedSense Team"
        )
        
        html_content = f"""
        <html>
        <body style="font-family: sans-serif; color: #333; line-height: 1.5;">
            <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
                <div style="background: #0f0c29; padding: 15px; text-align: center; border-radius: 8px 8px 0 0;">
                    <h1 style="color: white; margin: 0; font-size: 20px;">MedSense AI Report</h1>
                </div>
                <div style="padding: 20px;">
                    <p>Hello <strong>{patient_name}</strong>,</p>
                    <p>Your medical consultation report from your recent MedSense session is ready and attached to this email.</p>
                    <p>This report includes AI-driven diagnosis insights, bio-visual analysis, and recommended wellness measures.</p>
                    <br>
                    <p>Stay healthy,<br><strong>The MedSense Team</strong></p>
                </div>
                <div style="background: #f9fafb; padding: 15px; font-size: 11px; color: #6b7280; text-align: center; border-radius: 0 0 8px 8px;">
                    <p><strong>Disclaimer:</strong> This report is generated by an AI assistant for pre-consultation information only. it does not replace professional medical advice, diagnosis, or treatment.</p>
                </div>
            </div>
        </body>
        </html>
        """
        
        msg.set_content(text_content)
        msg.add_alternative(html_content, subtype='html')
        msg.add_attachment(pdf_bytes, maintype='application', subtype='pdf', filename='Medical_Report.pdf')

        print(f"Connecting to SMTP server {smtp_server}:{smtp_port}...")
        with smtplib.SMTP(smtp_server, smtp_port, timeout=20) as server:
            server.ehlo() # Identify ourselves to the server
            server.starttls() # Secure the connection
            server.ehlo() # Re-identify after TLS
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
            
        print(f"Report sent successfully to {to_email}")
        return True
    except smtplib.SMTPException as smtp_err:
        print(f"SMTP Protocol Error for {to_email}: {smtp_err}")
        return False
    except Exception as e:
        import traceback
        print(f"Failed to send email to {to_email} (Network/Server Error): {e}")
        # traceback.print_exc()
        return False

